### ISSUE TITLE
issue for task list

### ISSUE THREAD

**Issue by meenigar** [meenigar/markdown-portfolio#2]
[x] Additional markup is supported, including @mentions, #references, [links](url), **emphasis**, and <del>HTML tags</del>.
- [x] List syntax is required.
  - You can nest lists below, too!
- [x] This item is completed.
- [x] This item is not complete.
